### ISSUE TITLE
Form not being submitted by default or when 'data-submitForm="true"'

### ISSUE THREAD

**Issue by aengusbates** [Beanstream/beanstream-payform#2]
**Browsers:**
- All

**Steps to reproduce:**
- Configure Payform with either 'data-submitForm="true"', or 'data-submitForm' not set

**Expected behaviour:**
- Form wrapping Payform script should submit on completion

**Actual behaviour:**
- Form wrapping Payform script does not submit on completion

**Comment by aengusbates** [comment]
Fixed on master.

**Comment by aengusbates** [comment]
Fix verified on production.

**Comment by hughkolias** [comment]
hey @aengusbates - i'm still seeing the above issue with payfields. Has the hosted form been updated?

**Comment by aengusbates** [comment]
Hi Hugh,

Thanks for the feedback. The original fix was applied to Payform, but not
than Payfields. I'll apply the fix to Payfields.

You can work around this issue by setting `data-submitForm='true'` on the
script tag.

**Comment by hughkolias** [comment]
Thanks @aengusbates . I've tried the above workaround but I receive the following error in my console: 'Uncaught TypeError: self._view.form.submit is not a function'

Thanks for the help!

**Comment by aengusbates** [comment]
Np. Sounds like the script isn't the direct child of a form.

Here's a Plunker: https://plnkr.co/edit/4jycpwJqevixWMIYPxbO?p=preview

**Comment by hughkolias** [comment]
Ah - thanks for that. Had an extra <div> in there. Appreciate the help!

**Comment by aengusbates** [comment]
Reopening issue to track fix on Payfields.

**Comment by aengusbates** [comment]
Fix deployed.
