### ISSUE TITLE
Mixed content ssl content

### ISSUE THREAD

**Issue by jperanson** [Beanstream/beanstream-payform#9]
In beanstream-payform/payfields/assets/css/beanstream_payfields_style.css

Images should be loaded over https

cardType: function() {
                    var fieldType = _this._model.getFieldType();

                    if (fieldType === 'cc-number') {
                        var cardType = _this._model.getCardType();

                        if (cardType) {
                            if (cardType === 'maestro') {
                                cardType = 'mastercard';
                            }
                            if (cardType === 'visaelectron') {
                                cardType = 'visa';
                            }
                            _this._domInputElement.style.backgroundImage =
                                'url(**http://downloads.beanstream.com/images/payform/' + cardType + '.png**)';
                        } else {
                            _this._domInputElement.style.backgroundImage =
                                'url(**http://downloads.beanstream.com/images/payform/card.png**)';
                        }
                    }

**Comment by bowens-bambora** [comment]
We are working on migrating all of that data onto a new server that has our certificate so we can resolve the mixed content issue. It should be resolved soon, I will keep this issue open until that time.

**Comment by bowens-bambora** [comment]
Certs are being put in place and tested as we speak. Should have it deployed to production quite soon.

**Comment by wingzx3** [comment]
Is there a time frame for quite soon?  I am still seeing this issue.

**Comment by aengusbates** [comment]
The cert has been added to the bucket. I'll put in the code change this morning and see if we can deploy to production today. I'll update the thread when the change is live.

**Comment by aengusbates** [comment]
Fix live on prod.
